name: Build

on:
  - push

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: '[BUILD] | Install Dependencies'
        run: yarn download
        shell: bash

      - name: '[TEST] | Lint Check'
        run: yarn lint
        shell: bash
